### ISSUE TITLE
TrueNas 13.0-U3.1

### ISSUE THREAD

**Issue by Anian-igor** [fuji44/iocage-fuji44-plugins#1]
Hello.
I tried to install flexget on last version TrueNas 13.0-U3.1 but cannot..
```12.2-RELEASE was not found!```

Truenas has 12.3, 12.4, 13.0, 13.1

**Comment by fuji44** [comment]
Thanks for the report. It looks like it was EOL last March and no longer offered.

https://www.freebsd.org/ja/security/unsupported/

In my case, I migrated my host to TrueNAS 13.1, but did not notice it because I took over the Jail. Also, since I am using it on my internal network, I will continue to use it for a while.

It looks like you forked and upgraded to 13.1-RELEASE, did it work well?

**Comment by Anian-igor** [comment]
I don't have enough expiere with a jail. But I tried 13.1 and 12.3 ang got same 
Stopped due to VNET failure
I'm not sure if this related to my own setting or something else.

**Comment by fuji44** [comment]
I looked at the help for the iocage command and found the `--eol` option to get the EOL version.
I actually ran it in my environment and was able to build flexget without any problems.

For reference, here is the command I ran

```console
sudo iocage fetch -P flexget -n flexget2 --eol -g https://github.com/fuji44/iocage-fuji44-plugins.git ip4_addr="vnet0|192.168.10.254/24"
```

The `-n` option should be a name of your choice and the `ip4_addr` should be set according to your network environment.

**Comment by Anian-igor** [comment]
I installed success right now. Problem was with IP settings in my network.
But I got another problem. I cannot change config file. I got "Error" message in right down side of the screen. I found a file config.yml in jail and set 777 permission and flexget like an owner but without a luck

**Comment by fuji44** [comment]
I installed a new plugin and tried it. It is true that only "Error" is output. I can't figure out how to fix it, since the cause of the error is not output in the log either.

I tried manually starting flexget with the log level set to "debug," but it still did not output any useful logs.

By the way, the plugin I installed a few years ago can save config without any problem. flexget is version 3.3.38 and the permissions on config.yml were the same as in the newly installed state.

As it is, I can't determine if it's a flexget issue, permissions, or something else. First, I think you need to figure out what the flexget error is, and I suggest you talk to the flexget community.

https://flexget.com/en/NeedHelp

**Comment by Anian-igor** [comment]
I fixed anissue. Problem was with config as is. Not permissions. I replaced config with my working config from old system and right now all working fine.
Thanks a lot.
